'use client';

import React, { useState, useEffect } from 'react';

interface BackgroundImageProps {
  children: React.ReactNode;
  className?: string;
  bgIndex?: number;
  autoRotate?: boolean;
  rotationInterval?: number; // in milliseconds
}

const backgrounds = [
  '/bg/adelie_penguins.png',
  '/bg/airplan.png',
  '/bg/albatrosses.png',
  '/bg/alligators.png',
  '/bg/alpacas.png',
  '/bg/anacondas.png',
  '/bg/andean_condors.png',
  '/bg/anemones.png',
  '/bg/angelfishes.png',
  '/bg/antarctic_krill.png',
  '/bg/anteaters.png',
  '/bg/antelopes.png',
  '/bg/anzeday.png',
  '/bg/armadillos.png',
  '/bg/aurora02.png',
  '/bg/aurora1.png',
  '/bg/australia_day2.png',
  '/bg/autumntime1.png',
  '/bg/axolotls.png',
  '/bg/badgers.png',
  '/bg/Barracuda.png',
  '/bg/Barracudas.png',
  '/bg/bears.png',
  '/bg/birds.png',
  '/bg/bisons.png',
  '/bg/blue-whales.png',
  '/bg/bobcats.png',
  '/bg/box_jellyfishes.png',
  '/bg/budgerigars.png',
  '/bg/buffalos.png',
  '/bg/butterflies.png',
  '/bg/butterfly02.png',
  '/bg/camels.png',
  '/bg/canaryies.png',
  '/bg/capybaras.png',
  '/bg/cassowaries.png',
  '/bg/cats.png',
  '/bg/chamoises.png',
  '/bg/cheetahs.png',
  '/bg/chickens.png',
  '/bg/chimpanzees.png',
  '/bg/chinchillas.png',
  '/bg/chinese_dragon.png',
  '/bg/chinese_new_year.png',
  '/bg/chirstmas.png',
  '/bg/clams.png',
  '/bg/clams1.png',
  '/bg/clams2.png',
  '/bg/clownfishes.png',
  '/bg/cockatoo.png',
  '/bg/cockatoos.png',
  '/bg/corals.png',
  '/bg/cows.png',
  '/bg/crabs.png',
  '/bg/crocodiles.png',
  '/bg/cuttlefishes.png',
  '/bg/daytimebg2.png',
  '/bg/deers.png',
  '/bg/dingos.png',
  '/bg/dogs.png',
  '/bg/dogs1.png',
  '/bg/dolphin_fishes.png',
  '/bg/dolphins.png',
  '/bg/donkeys.png',
  '/bg/doves.png',
  '/bg/dragon.png',
  '/bg/dragonfly.png',
  '/bg/dragonfly01.png',
  '/bg/drone_show.png',
  '/bg/drone.png',
  '/bg/ducks.png',
  '/bg/duststorm1.png',
  '/bg/duststorm2.png',
  '/bg/eagle.png',
  '/bg/echidnas.png',
  '/bg/eels.png',
  '/bg/electric_eels.png',
  '/bg/elephants.png',
  '/bg/elephants1.png',
  '/bg/emperor_penguin.png',
  '/bg/emperor_penguins.png',
  '/bg/emus.png',
  '/bg/ester.png',
  '/bg/eurasian_lynxes.png',
  '/bg/falcons.png',
  '/bg/falkor_the_luckdrago.png',
  '/bg/ferrets.png',
  '/bg/fighter_jet.png',
  '/bg/fish.png',
  '/bg/flying_fishes.png',
  '/bg/forgs.png',
  '/bg/foxes.png',
  '/bg/frilled-lizards.png',
  '/bg/frogs.png',
  '/bg/giraffes.png',
  '/bg/glider_fly.png',
  '/bg/goats.png',
  '/bg/goats1.png',
  '/bg/golden_eagles.png',
  '/bg/goldfishs.png',
  '/bg/goldfishs1.png',
  '/bg/gooses.png',
  '/bg/gorillas.png',
  '/bg/gorillas1.png',
  '/bg/griffin.png',
  '/bg/grizzly_bears.png',
  '/bg/guinea_pigs.png',
  '/bg/hail_storm.png',
  '/bg/hail_storm01.png',
  '/bg/hammerhead_sharks1.png',
  '/bg/hamsters.png',
  '/bg/hawks.png',
  '/bg/hedgehogs.png',
  '/bg/hedgehogs1.png',
  '/bg/helicopter.png',
  '/bg/highland_cattles.png',
  '/bg/hippopotamuses.png',
  '/bg/horses.png',
  '/bg/horseshoe_crabs.png',
  '/bg/horseshoe_crabs1.png',
  '/bg/hot air balloon.png',
  '/bg/hyenas.png',
  '/bg/indian_star_tortoises.png',
  '/bg/jaguars.png',
  '/bg/jaguars1.png',
  '/bg/jellyfishs.png',
  '/bg/kangaroos.png',
  '/bg/kids_day1.png',
  '/bg/kits01.png',
  '/bg/kits02.png',
  '/bg/koalas.png',
  '/bg/komodo dragons.png',
  '/bg/koreanday.png',
  '/bg/leopard_seal.png',
  '/bg/leopards.png',
  '/bg/lions.png',
  '/bg/llamas.png',
  '/bg/lobsters.png',
  '/bg/lovebirds.png',
  '/bg/macaws.png',
  '/bg/maned_wolfs.png',
  '/bg/manta_raies.png',
  '/bg/meteorite.png',
  '/bg/monkeys.png',
  '/bg/mooses.png',
  '/bg/mothers_day.png',
  '/bg/mouflons.png',
  '/bg/mouflons1.png',
  '/bg/mountain_lions.png',
  '/bg/mouses.png',
  '/bg/mussels.png',
  '/bg/narwhals.png',
  '/bg/nautiluses.png',
  '/bg/new_year1.png',
  '/bg/nightbg3.png',
  '/bg/octopuses.png',
  '/bg/octopuses1.png',
  '/bg/opossums.png',
  '/bg/orangutans.png',
  '/bg/orcas.png',
  '/bg/otters.png',
  '/bg/owls.png',
  '/bg/owls2.png',
  '/bg/oysters.png',
  '/bg/pandas.png',
  '/bg/paraglider.png',
  '/bg/parrots.png',
  '/bg/peacocks.png',
  '/bg/pegasus.png',
  '/bg/pelicans.png',
  '/bg/penguins.png',
  '/bg/phoenix.png',
  '/bg/pigeons.png',
  '/bg/pigs.png',
  '/bg/piranhas.png',
  '/bg/platypuses.png',
  '/bg/poison_dart_frogs.png',
  '/bg/poison_dart_frogs1.png',
  '/bg/ponies.png',
  '/bg/porcupines.png',
  '/bg/prawns.png',
  '/bg/pufferfishes.png',
  '/bg/quails.png',
  '/bg/rabbits.png',
  '/bg/raccoons.png',
  '/bg/rainbow1.png',
  '/bg/rainingday01.png',
  '/bg/rainingday02.png',
  '/bg/rats.png',
  '/bg/red_pandas.png',
  '/bg/rhinoceroses.png',
  '/bg/rocket.png',
  '/bg/salmons.png',
  '/bg/salmons1.png',
  '/bg/scallops.png',
  '/bg/sea_turtles.png',
  '/bg/sea_turtles1.png',
  '/bg/sea_lions.png',
  '/bg/sea_urchins.png',
  '/bg/seahorses.png',
  '/bg/seals.png',
  '/bg/sharks.png',
  '/bg/sharks1.png',
  '/bg/sharks2.png',
  '/bg/sheet.png',
  '/bg/shooting_starts.png',
  '/bg/shooting_starts01.png',
  '/bg/shrimps.png',
  '/bg/silkworms.png',
  '/bg/skydiver.png',
  '/bg/sloths.png',
  '/bg/snow_petrels.png',
  '/bg/snowleopards.png',
  '/bg/spacecraft.png',
  '/bg/spring.png',
  '/bg/springtime01.png',
  '/bg/squids.png',
  '/bg/starfishes.png',
  '/bg/stingraies.png',
  '/bg/summerday1.png',
  '/bg/swans.png',
  '/bg/swordfishes.png',
  '/bg/swordfishes1.png',
  '/bg/tasmanian_devils.png',
  '/bg/tigers.png',
  '/bg/timber_wolfs.png',
  '/bg/tornadoday1.png',
  '/bg/turkeies.png',
  '/bg/turtle.png',
  '/bg/ufo.png',
  '/bg/ufo1.png',
  '/bg/underwater.png',
  '/bg/unicorns.png',
  '/bg/volcanic_eruptions.png',
  '/bg/vultures.png',
  '/bg/walruses.png',
  '/bg/water.png',
  '/bg/Weddell_seals.png',
  '/bg/weddell_seal.png',
  '/bg/whales.png',
  '/bg/wild_boars.png',
  '/bg/windyday1.png',
  '/bg/winterday02.png',
  '/bg/wolfs.png',
  '/bg/wolverines.png',
  '/bg/wombats.png',
  '/bg/yaks.png',
  '/bg/zebra.png',
  '/bg/zebras.png',
  '/bg/zebras1.png'
];

export const BackgroundImage: React.FC<BackgroundImageProps> = ({
  children,
  className = '',
  bgIndex,
  autoRotate = false,
  rotationInterval = 30000 // 30 seconds default
}) => {
  const [currentBgIndex, setCurrentBgIndex] = useState(bgIndex || 0);

  useEffect(() => {
    if (autoRotate) {
      const interval = setInterval(() => {
        setCurrentBgIndex((prev) => (prev + 1) % backgrounds.length);
      }, rotationInterval);

      return () => clearInterval(interval);
    }
  }, [autoRotate, rotationInterval]);

  const backgroundStyle = {
    backgroundImage: `url(${backgrounds[currentBgIndex]})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: 'fixed'
  };

  return (
    <div
      className={`min-h-screen ${className}`}
      style={backgroundStyle}
    >
      {children}
    </div>
  );
};

// Export the backgrounds array for use in other components
export { backgrounds }; 